<?php

// autoload-classmap.php @generated by Strauss

$srcDependencies = dirname(__FILE__);

return array(
   'MZoo\MzMindbody\Dependencies\EAMann\Sessionz\Handler' => $srcDependencies . '/ericmann/sessionz/php/Handler.php',
   'MZoo\MzMindbody\Dependencies\EAMann\Sessionz\Objects\MemoryItem' => $srcDependencies . '/ericmann/sessionz/php/Objects/MemoryItem.php',
   'MZoo\MzMindbody\Dependencies\EAMann\Sessionz\Manager' => $srcDependencies . '/ericmann/sessionz/php/Manager.php',
   'MZoo\MzMindbody\Dependencies\EAMann\Sessionz\Handlers\NoopHandler' => $srcDependencies . '/ericmann/sessionz/php/Handlers/NoopHandler.php',
   'MZoo\MzMindbody\Dependencies\EAMann\Sessionz\Handlers\EncryptionHandler' => $srcDependencies . '/ericmann/sessionz/php/Handlers/EncryptionHandler.php',
   'MZoo\MzMindbody\Dependencies\EAMann\Sessionz\Handlers\DefaultHandler' => $srcDependencies . '/ericmann/sessionz/php/Handlers/DefaultHandler.php',
   'MZoo\MzMindbody\Dependencies\EAMann\Sessionz\Handlers\BaseHandler' => $srcDependencies . '/ericmann/sessionz/php/Handlers/BaseHandler.php',
   'MZoo\MzMindbody\Dependencies\EAMann\Sessionz\Handlers\MemoryHandler' => $srcDependencies . '/ericmann/sessionz/php/Handlers/MemoryHandler.php',
   'MZoo\MzMindbody\Dependencies\EAMann\WPSession\Objects\Option' => $srcDependencies . '/ericmann/wp-session-manager/includes/Option.php',
   'MZoo\MzMindbody\Dependencies\EAMann\WPSession\DatabaseHandler' => $srcDependencies . '/ericmann/wp-session-manager/includes/DatabaseHandler.php',
   'MZoo\MzMindbody\Dependencies\EAMann\WPSession\OptionsHandler' => $srcDependencies . '/ericmann/wp-session-manager/includes/OptionsHandler.php',
   'MZoo\MzMindbody\Dependencies\EAMann\WPSession\SessionHandler' => $srcDependencies . '/ericmann/wp-session-manager/includes/SessionHandler.php',
   'MZoo\MzMindbody\Dependencies\EAMann\WPSession\CacheHandler' => $srcDependencies . '/ericmann/wp-session-manager/includes/CacheHandler.php',
   'MZoo_MzMindbody_WP_Session' => $srcDependencies . '/ericmann/wp-session-manager/includes/deprecated.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\Crypto' => $srcDependencies . '/defuse/php-encryption/src/Crypto.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\KeyProtectedByPassword' => $srcDependencies . '/defuse/php-encryption/src/KeyProtectedByPassword.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\Key' => $srcDependencies . '/defuse/php-encryption/src/Key.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\File' => $srcDependencies . '/defuse/php-encryption/src/File.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\KeyOrPassword' => $srcDependencies . '/defuse/php-encryption/src/KeyOrPassword.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\Encoding' => $srcDependencies . '/defuse/php-encryption/src/Encoding.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\DerivedKeys' => $srcDependencies . '/defuse/php-encryption/src/DerivedKeys.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\RuntimeTests' => $srcDependencies . '/defuse/php-encryption/src/RuntimeTests.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\Exception\BadFormatException' => $srcDependencies . '/defuse/php-encryption/src/Exception/BadFormatException.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\Exception\CryptoException' => $srcDependencies . '/defuse/php-encryption/src/Exception/CryptoException.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\Exception\EnvironmentIsBrokenException' => $srcDependencies . '/defuse/php-encryption/src/Exception/EnvironmentIsBrokenException.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\Exception\IOException' => $srcDependencies . '/defuse/php-encryption/src/Exception/IOException.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\Exception\WrongKeyOrModifiedCiphertextException' => $srcDependencies . '/defuse/php-encryption/src/Exception/WrongKeyOrModifiedCiphertextException.php',
   'MZoo\MzMindbody\Dependencies\Defuse\Crypto\Core' => $srcDependencies . '/defuse/php-encryption/src/Core.php',
   'MZoo_MzMindbody_Gamajo_Template_Loader' => $srcDependencies . '/gamajo/template-loader/class-gamajo-template-loader.php',
);