<?php

// autoload-classmap.php @generated by Strauss

$srcDependencies = dirname(__FILE__);

return array(
   'MZoo_MzMindbody_Gamajo_Template_Loader' => $srcDependencies . '/gamajo/template-loader/class-gamajo-template-loader.php',
);